# Pipeline GitLab CI pour construire, tester, publier et déployer une image Docker
stages:
  - build
  - test
  - release
  - deploy

# Variables globales utilisées dans les différents jobs
variables:
  IMAGE_TAG: 'v1.0'
  IMAGE_NAME: 'mini-projet-gitlab-ci'
  DOCKER_USERNAME: 'gastech'
  #DOCKER_PASSWORD:
  HOST_PORT: 80
  CONTAINER_PORT: 80
  SERVER_USERNAME: 'ubuntu'

# Étape de build : construction de l'image Docker et sauvegarde de l'archive
build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - docker build --no-cache -t $IMAGE_NAME:$IMAGE_TAG .
    - docker save -o mini-projet-gitlab-ci.tar $IMAGE_NAME:$IMAGE_TAG
  artifacts:
    paths:
      - mini-projet-gitlab-ci.tar

# Modèle réutilisable pour les tests d'intégration
.test_template: &test_template
  stage: test
  before_script:
    - apk add --no-cache curl
  script:
    - docker load -i mini-projet-gitlab-ci.tar
    - docker run --rm -dp $HOST_PORT:$CONTAINER_PORT --name $IMAGE_NAME $IMAGE_NAME:$IMAGE_TAG
    - sleep 5
    - curl -f http://docker | grep -i 200

# Job de test qui réutilise le modèle ci-dessus
test:
  stage: test
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  <<: *test_template

# Modèle réutilisable pour la publication de l'image sur Docker Hub
.release_image: &release_image
  stage: release
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker load -i mini-projet-gitlab-ci.tar
    - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
    - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

# Job de release qui publie l'image Docker
release:
  stage: release
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  <<: *release_image

# Modèle réutilisable pour le déploiement sur un serveur distant
.deploy_app: &deploy_app
  stage: deploy
  before_script:
    - apk add --no-cache openssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d > /tmp/id_rsa
    - chmod 600 /tmp/id_rsa
    - ssh-add /tmp/id_rsa
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa $SERVER_USERNAME@$SERVER_IP "docker pull $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG"
    - ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa $SERVER_USERNAME@$SERVER_IP "docker run --rm -dp $HOST_PORT:$CONTAINER_PORT --name $IMAGE_NAME $IMAGE_NAME:$IMAGE_TAG"

# Déploiement sur l'environnement de review
deploy review:
  stage: deploy
  image: alpine
  <<: *deploy_app
  environment:
    name: Review/$CI_COMMIT_REF_NAME

# Déploiement sur l'environnement staging
Deploy Staging:
  stage: deploy
  image: alpine
  <<: *deploy_app
  environment:
    name: Staging

# Déploiement sur l'environnement production
Deploy Production:
  stage: deploy
  image: alpine
  <<: *deploy_app
  environment:
    name: Production